name: kaldi-boothroyd

channels:
  - pytorch
  - conda-forge

dependencies:
  - compilers
  - jupyter
  - kaldi=*=cuda*
  - libflac
  - perl
  - pingouin
  - pip
  - plotly
  - pydrobert-kaldi
  - python<3.12
  - python-kaleido
  - pytorch=*=cuda*
  - pytorch-mutex=*=cuda
  - sox
  - transformers
  - huggingface_hub
  - sentencepiece
  - ruamel.yaml
  - numba
  - pip:
    - recombinator
    - git+https://github.com/sdrobert/kenlm.git
