name: kaldi-boothroyd

channels:
  - conda-forge

dependencies:
  - compilers
  - jupyter
  - kaldi
  - libflac
  - perl
  - pip
  - pydrobert-kaldi
  - python
  - seaborn
  - sox
  - pip:
    - git+https://github.com/sdrobert/kenlm.git
