name: kaldi-boothroyd

channels:
  - conda-forge

dependencies:
  - compilers
  - kaldi
  - libflac
  - perl
  - pip
  - python=3.11
  - pydrobert-kaldi
  - sox
  - pip:
    - git+https://github.com/sdrobert/kenlm.git
